package co.jinear.core.model.enumtype.notification;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum NotificationType {
    TASK_REMINDER(0),
    WORKSPACE_ACTIVITY(1),
    TASK_INITIALIZED(2),
    TASK_CLOSED(3),
    EDIT_TASK_TITLE(4),
    EDIT_TASK_DESC(5),
    TASK_UPDATE_TOPIC(6),
    TASK_UPDATE_WORKFLOW_STATUS(7),
    TASK_CHANGE_ASSIGNEE(8),
    TASK_CHANGE_ASSIGNED_DATE(9),
    TASK_CHANGE_DUE_DATE(10),
    RELATION_INITIALIZED(11),
    RELATION_REMOVED(12),
    CHECKLIST_INITIALIZED(13),
    CHECKLIST_REMOVED(14),
    CHECKLIST_TITLE_CHANGED(15),
    CHECKLIST_ITEM_CHECKED_STATUS_CHANGED(16),
    CHECKLIST_ITEM_LABEL_CHANGED(17),
    CHECKLIST_ITEM_REMOVED(18),
    CHECKLIST_ITEM_INITIALIZED(19),
    TASK_NEW_COMMENT(20),
    MESSAGING_NEW_MESSAGE_THREAD(30),
    MESSAGING_NEW_MESSAGE_CONVERSATION(31);

    private final int value;
}
