package co.jinear.core.mcp;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import co.jinear.core.model.enumtype.mcp.McpScope;
import co.jinear.core.service.mcp.tool.McpTool;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

/**
 * Keeps the published tool documentation honest.
 * <p>
 * jinear-site renders one page per tool from a JSON manifest. That manifest is this
 * server's own tools/list output, checked in, so a description or a schema cannot drift
 * from the running server without this test failing and naming the fix.
 */
class McpToolManifestExportTest {

    private static final Path MANIFEST = Paths.get("..", "jinear-site", "lib", "mcp-tools.generated.json");

    private final ObjectMapper objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

    private ObjectNode scopesOf() {
        ObjectNode scopes = objectMapper.createObjectNode();
        for (McpTool tool : McpRealCatalog.registry().all()) {
            ArrayNode required = scopes.putArray(tool.name());
            // Sorted, because Set.of has a per run iteration order. Without this the
            // manifest would differ between runs and the comparison below would flap.
            tool.definition().getRequiredScopes().stream()
                    .map(McpScope::getValue)
                    .sorted()
                    .forEach(required::add);
        }
        return scopes;
    }

    @Test
    void theCheckedInManifestMatchesTheLiveToolCatalog() throws Exception {
        ObjectNode manifest = objectMapper.createObjectNode();
        manifest.put("$comment", "Generated by McpToolManifestExportTest in jinear-core. Do not edit by hand.");
        manifest.set("tools", McpRealCatalog.registry().toolsArray());
        // The tools array stays exactly what tools/list returns, so it cannot drift from
        // the protocol shape. Scopes are not part of that shape, so they ride alongside:
        // the published page groups tools by the permission they ask for, and deriving
        // that on the site would duplicate knowledge that lives in the tool definitions.
        manifest.set("scopes", scopesOf());
        String rendered = objectMapper.writeValueAsString(manifest) + "\n";

        if (!Files.exists(MANIFEST)) {
            // First run after the docs pages are added: write it rather than fail on a
            // file that has never existed.
            Files.createDirectories(MANIFEST.getParent());
            Files.writeString(MANIFEST, rendered, StandardCharsets.UTF_8);
            return;
        }

        String committed = Files.readString(MANIFEST, StandardCharsets.UTF_8);
        if (!committed.equals(rendered)) {
            Path actual = MANIFEST.resolveSibling("mcp-tools.generated.json.actual");
            Files.writeString(actual, rendered, StandardCharsets.UTF_8);
            fail("The MCP tool catalog changed but jinear-site/lib/mcp-tools.generated.json was not regenerated. "
                    + "The new manifest has been written to " + actual.toAbsolutePath()
                    + ". Move it over the committed file and commit both together, so the published tool "
                    + "documentation matches the server.");
        }
        assertThat(committed).isEqualTo(rendered);
    }
}
