package co.jinear.core.mcp;

import co.jinear.core.manager.mcp.tool.McpTool;
import co.jinear.core.model.enumtype.oauth.OauthScope;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

/**
 * Publishes the MCP tool catalog that jinear-site renders on its /mcp page.
 * <p>
 * Run {@link #main} by hand before committing a tool change, then commit the refreshed
 * jinear-site file alongside it. {@code McpToolManifestExportTest} only reads, so a stale
 * manifest fails the build without any test writing to the working tree.
 * <p>
 * This lives in test sources because building the catalog needs the mocked managers in
 * {@link McpRealCatalog}, and none of it belongs in the shipped jar.
 */
public final class McpToolManifestExporter {

    private static final String FILE_NAME = "mcp-tools.generated.json";

    /**
     * Working copy, written next to the code that produces it. Gitignored.
     */
    static final Path GENERATED = Paths.get(FILE_NAME);

    /**
     * The committed copy jinear-site imports at build time.
     */
    static final Path PUBLISHED = Paths.get("..", "jinear-site", "lib", FILE_NAME);

    private static final ObjectMapper OBJECT_MAPPER =
            new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

    private McpToolManifestExporter() {
    }

    public static void main(String[] args) throws IOException {
        generateAndPublish();
    }

    /**
     * Renders the catalog and writes it to the jinear-core working copy.
     */
    public static Path generate() throws IOException {
        Files.writeString(GENERATED, render(), StandardCharsets.UTF_8);
        return GENERATED.toAbsolutePath();
    }

    /**
     * Copies the working copy over the file jinear-site imports. Run {@link #generate()} first.
     */
    public static Path publish() throws IOException {
        if (!Files.exists(GENERATED)) {
            throw new IllegalStateException("Nothing to publish. Run generate() first: " + GENERATED.toAbsolutePath());
        }
        Files.createDirectories(PUBLISHED.getParent());
        Files.copy(GENERATED, PUBLISHED, StandardCopyOption.REPLACE_EXISTING);
        return PUBLISHED.toAbsolutePath();
    }

    /**
     * Generates, then publishes.
     */
    public static void generateAndPublish() throws IOException {
        Path generated = generate();
        Path published = publish();
        System.out.println("Generated " + generated);
        System.out.println("Published " + published);
        System.out.println("Commit the jinear-site file with the tool change.");
    }

    /**
     * The manifest as it should appear on disk, used by the exporter and by the test that
     * checks the committed copy is current.
     */
    static String render() {
        ObjectNode manifest = OBJECT_MAPPER.createObjectNode();
        manifest.put("$comment", "Generated by McpToolManifestExporter in jinear-core. Do not edit by hand.");
        manifest.set("tools", OBJECT_MAPPER.valueToTree(McpRealCatalog.registry().descriptors()));
        manifest.set("scopes", scopes());
        return writeAsString(manifest) + "\n";
    }

    private static ObjectNode scopes() {
        ObjectNode scopes = OBJECT_MAPPER.createObjectNode();
        for (McpTool tool : McpRealCatalog.registry().all()) {
            ArrayNode required = scopes.putArray(tool.name());
            tool.definition().getRequiredScopes().stream()
                    .map(OauthScope::getValue)
                    .sorted()
                    .forEach(required::add);
        }
        return scopes;
    }

    private static String writeAsString(ObjectNode manifest) {
        try {
            return OBJECT_MAPPER.writeValueAsString(manifest);
        } catch (JsonProcessingException exception) {
            throw new IllegalStateException("The MCP tool manifest could not be rendered.", exception);
        }
    }
}
