package co.jinear.core.model.enumtype.workspace;

import lombok.Getter;

@Getter
public enum WorkspaceActivityType {
    MEMBER_JOIN,
    MEMBER_LEFT,
    MEMBER_REMOVED,
    MEMBER_REQUESTED_ACCESS,
    //task stuff
    TASK_INITIALIZED,
    TASK_CLOSED,
    EDIT_TASK_TITLE,
    EDIT_TASK_DESC,
    TASK_UPDATE_TOPIC,
    TASK_UPDATE_WORKFLOW_STATUS,
    TASK_CHANGE_ASSIGNEE,
    TASK_CHANGE_ASSIGNED_DATE,
    TASK_CHANGE_DUE_DATE,
    RELATION_INITIALIZED,
    RELATION_REMOVED,
    CHECKLIST_INITIALIZED,
    CHECKLIST_REMOVED,
    CHECKLIST_TITLE_CHANGED,
    CHECKLIST_ITEM_CHECKED_STATUS_CHANGED,
    CHECKLIST_ITEM_LABEL_CHANGED,
    CHECKLIST_ITEM_REMOVED,
    CHECKLIST_ITEM_INITIALIZED,
    ATTACHMENT_ADDED,
    ATTACHMENT_DELETED,
    //task-board-entry
    TASK_BOARD_ENTRY_INIT,
    TASK_BOARD_ENTRY_REMOVED,
    TASK_BOARD_ENTRY_ORDER_CHANGE,
}
