import type {ThemeDefinition} from "@/theme/themeTypes";

// Themes that ship with IntelliJ IDEA and the other JetBrains IDEs.
export const jetbrainsThemes: ThemeDefinition[] = [
    {
        id: "jetbrains-dark",
        name: "Dark",
        origin: "jetbrains",
        appearance: "dark",
        palette: {
            background: "#1e1f22",
            surface: "#2b2d30",
            border: "#393b40",
            text: "#dfe1e5",
            link: "#548af7",
            accent: "#3574f0",
            onAccent: "#ffffff",
            danger: "#f75464",
            success: "#5fb865",
            selection: "#214283",
            caret: "#ced0d6",
        },
    },
    {
        id: "jetbrains-light",
        name: "Light",
        origin: "jetbrains",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#f7f8fa",
            border: "#ebecf0",
            text: "#000000",
            link: "#2e55a3",
            accent: "#3574f0",
            onAccent: "#ffffff",
            danger: "#db3b4b",
            success: "#208a3c",
            selection: "#a6d2ff",
            caret: "#000000",
        },
    },
    {
        id: "jetbrains-darcula",
        name: "Darcula",
        origin: "jetbrains",
        appearance: "dark",
        palette: {
            background: "#2b2b2b",
            surface: "#3c3f41",
            border: "#515151",
            text: "#bbbbbb",
            link: "#589df6",
            accent: "#4a88c7",
            onAccent: "#ffffff",
            danger: "#ff6b68",
            success: "#499c54",
            selection: "#214283",
            caret: "#bbbbbb",
        },
    },
    {
        id: "jetbrains-intellij-light",
        name: "IntelliJ Light",
        origin: "jetbrains",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#f2f2f2",
            border: "#d1d1d1",
            text: "#000000",
            link: "#2470b3",
            accent: "#4083c9",
            onAccent: "#ffffff",
            danger: "#db5c5c",
            success: "#3d8f58",
            selection: "#a6d2ff",
            caret: "#000000",
        },
    },
    {
        id: "jetbrains-dark-purple",
        name: "Dark Purple",
        origin: "jetbrains",
        appearance: "dark",
        palette: {
            background: "#2b2838",
            surface: "#353145",
            border: "#433e57",
            text: "#d4d0e0",
            link: "#a78bfa",
            accent: "#7b5fc9",
            onAccent: "#ffffff",
            danger: "#f47067",
            success: "#6cc070",
            selection: "#4a3f73",
            caret: "#d4d0e0",
        },
    },
    {
        id: "jetbrains-cyan-light",
        name: "Cyan Light",
        origin: "jetbrains",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#eef6f7",
            border: "#cfe2e5",
            text: "#1c2b2e",
            link: "#0b7a8a",
            accent: "#0f7e8c",
            onAccent: "#ffffff",
            danger: "#c7322f",
            success: "#2f8a3e",
            selection: "#bfe6ea",
            caret: "#1c2b2e",
        },
    },
];
