import type {ThemeDefinition} from "@/theme/themeTypes";

// Popular community themes, most of them available for both VS Code and JetBrains IDEs.
export const popularThemes: ThemeDefinition[] = [
    {
        id: "one-dark-pro",
        name: "One Dark Pro",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#282c34",
            surface: "#2f343e",
            border: "#3e4452",
            text: "#abb2bf",
            link: "#61afef",
            accent: "#61afef",
            onAccent: "#282c34",
            danger: "#e06c75",
            success: "#98c379",
            selection: "#3e4451",
            caret: "#528bff",
        },
    },
    {
        id: "atom-one-light",
        name: "Atom One Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#fafafa",
            surface: "#eaeaeb",
            border: "#dbdbdc",
            text: "#383a42",
            link: "#4078f2",
            accent: "#4078f2",
            onAccent: "#ffffff",
            danger: "#e45649",
            success: "#50a14f",
            selection: "#e5e5e6",
            caret: "#526fff",
        },
    },
    {
        id: "dracula",
        name: "Dracula",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#282a36",
            surface: "#343746",
            border: "#44475a",
            text: "#f8f8f2",
            link: "#8be9fd",
            accent: "#bd93f9",
            onAccent: "#282a36",
            danger: "#ff5555",
            success: "#50fa7b",
            selection: "#44475a",
            caret: "#f8f8f0",
        },
    },
    {
        id: "github-dark",
        name: "GitHub Dark",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#0d1117",
            surface: "#161b22",
            border: "#30363d",
            text: "#e6edf3",
            link: "#4493f8",
            accent: "#238636",
            onAccent: "#ffffff",
            danger: "#f85149",
            success: "#3fb950",
            selection: "#1f3a5f",
            caret: "#e6edf3",
        },
    },
    {
        id: "github-dark-dimmed",
        name: "GitHub Dark Dimmed",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#22272e",
            surface: "#2d333b",
            border: "#444c56",
            text: "#adbac7",
            link: "#539bf5",
            accent: "#347d39",
            onAccent: "#ffffff",
            danger: "#e5534b",
            success: "#57ab5a",
            selection: "#264366",
            caret: "#539bf5",
        },
    },
    {
        id: "github-light",
        name: "GitHub Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#f6f8fa",
            border: "#d0d7de",
            text: "#1f2328",
            link: "#0969da",
            accent: "#1f883d",
            onAccent: "#ffffff",
            danger: "#d1242f",
            success: "#1a7f37",
            selection: "#cde1f8",
            caret: "#0969da",
        },
    },
    {
        id: "night-owl",
        name: "Night Owl",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#011627",
            surface: "#0b2942",
            border: "#1d3b53",
            text: "#d6deeb",
            link: "#82aaff",
            accent: "#7e57c2",
            onAccent: "#ffffff",
            danger: "#ef5350",
            success: "#addb67",
            selection: "#1d3b53",
            caret: "#80a4c2",
        },
    },
    {
        id: "night-owl-light",
        name: "Night Owl Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#fbfbfb",
            surface: "#f0f0f0",
            border: "#d9d9d9",
            text: "#403f53",
            link: "#4876d6",
            accent: "#2aa298",
            danger: "#de3d3b",
            success: "#08916a",
            selection: "#e0e0e0",
            caret: "#90a7b2",
        },
    },
    {
        id: "nord",
        name: "Nord",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#2e3440",
            surface: "#3b4252",
            border: "#434c5e",
            text: "#d8dee9",
            link: "#88c0d0",
            accent: "#88c0d0",
            onAccent: "#2e3440",
            danger: "#bf616a",
            success: "#a3be8c",
            selection: "#434c5e",
            caret: "#d8dee9",
        },
    },
    {
        id: "tokyo-night",
        name: "Tokyo Night",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1a1b26",
            surface: "#1f2335",
            border: "#292e42",
            text: "#c0caf5",
            link: "#7aa2f7",
            accent: "#7aa2f7",
            onAccent: "#1a1b26",
            danger: "#f7768e",
            success: "#9ece6a",
            selection: "#283457",
            caret: "#c0caf5",
        },
    },
    {
        id: "tokyo-night-storm",
        name: "Tokyo Night Storm",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#24283b",
            surface: "#1f2335",
            border: "#3b4261",
            text: "#c0caf5",
            link: "#7aa2f7",
            accent: "#bb9af7",
            onAccent: "#24283b",
            danger: "#f7768e",
            success: "#9ece6a",
            selection: "#364a82",
            caret: "#c0caf5",
        },
    },
    {
        id: "tokyo-night-light",
        name: "Tokyo Night Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#e1e2e7",
            surface: "#d0d5e3",
            border: "#c4c8da",
            text: "#3760bf",
            link: "#2e7de9",
            accent: "#2e7de9",
            onAccent: "#ffffff",
            danger: "#f52a65",
            success: "#587539",
            selection: "#b7c1e3",
            caret: "#3760bf",
        },
    },
    {
        id: "catppuccin-latte",
        name: "Catppuccin Latte",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#eff1f5",
            surface: "#e6e9ef",
            border: "#ccd0da",
            text: "#4c4f69",
            textSubtle: "#5c5f77",
            link: "#1e66f5",
            accent: "#8839ef",
            onAccent: "#eff1f5",
            danger: "#d20f39",
            success: "#40a02b",
            selection: "#bcc0cc",
            caret: "#dc8a78",
        },
    },
    {
        id: "catppuccin-frappe",
        name: "Catppuccin Frappé",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#303446",
            surface: "#414559",
            border: "#51576d",
            text: "#c6d0f5",
            textMuted: "#b5bfe2",
            textSubtle: "#a5adce",
            link: "#8caaee",
            accent: "#ca9ee6",
            onAccent: "#303446",
            danger: "#e78284",
            success: "#a6d189",
            selection: "#51576d",
            caret: "#f2d5cf",
        },
    },
    {
        id: "catppuccin-macchiato",
        name: "Catppuccin Macchiato",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#24273a",
            surface: "#363a4f",
            border: "#494d64",
            text: "#cad3f5",
            textMuted: "#b8c0e0",
            textSubtle: "#a5adcb",
            link: "#8aadf4",
            accent: "#c6a0f6",
            onAccent: "#24273a",
            danger: "#ed8796",
            success: "#a6da95",
            selection: "#494d64",
            caret: "#f4dbd6",
        },
    },
    {
        id: "catppuccin-mocha",
        name: "Catppuccin Mocha",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1e1e2e",
            surface: "#313244",
            border: "#45475a",
            text: "#cdd6f4",
            textMuted: "#bac2de",
            textSubtle: "#a6adc8",
            link: "#89b4fa",
            accent: "#cba6f7",
            onAccent: "#1e1e2e",
            danger: "#f38ba8",
            success: "#a6e3a1",
            selection: "#45475a",
            caret: "#f5e0dc",
        },
    },
    {
        id: "gruvbox-dark",
        name: "Gruvbox Dark",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#282828",
            surface: "#3c3836",
            border: "#504945",
            text: "#ebdbb2",
            link: "#83a598",
            accent: "#fe8019",
            onAccent: "#282828",
            danger: "#fb4934",
            success: "#b8bb26",
            selection: "#504945",
            caret: "#ebdbb2",
        },
    },
    {
        id: "gruvbox-light",
        name: "Gruvbox Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#fbf1c7",
            surface: "#ebdbb2",
            border: "#d5c4a1",
            text: "#3c3836",
            link: "#076678",
            accent: "#af3a03",
            onAccent: "#fbf1c7",
            danger: "#9d0006",
            success: "#79740e",
            selection: "#d5c4a1",
            caret: "#3c3836",
        },
    },
    {
        id: "ayu-dark",
        name: "Ayu Dark",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#0b0e14",
            surface: "#131721",
            border: "#1e222a",
            text: "#bfbdb6",
            link: "#39bae6",
            accent: "#e6b450",
            onAccent: "#0b0e14",
            danger: "#d95757",
            success: "#aad94c",
            selection: "#273747",
            caret: "#e6b450",
        },
    },
    {
        id: "ayu-mirage",
        name: "Ayu Mirage",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1f2430",
            surface: "#242936",
            border: "#33415e",
            text: "#cccac2",
            link: "#73d0ff",
            accent: "#ffcc66",
            onAccent: "#1f2430",
            danger: "#ff6666",
            success: "#d5ff80",
            selection: "#33415e",
            caret: "#ffcc66",
        },
    },
    {
        id: "ayu-light",
        name: "Ayu Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#fcfcfc",
            surface: "#f3f4f5",
            border: "#e6e8ea",
            text: "#5c6166",
            link: "#1f7fc4",
            accent: "#ffaa33",
            danger: "#e65050",
            success: "#86b300",
            selection: "#d3e1f5",
            caret: "#ffaa33",
        },
    },
    {
        id: "material-oceanic",
        name: "Material Oceanic",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#263238",
            surface: "#2e3c43",
            border: "#37474f",
            text: "#eeffff",
            textSubtle: "#b0bec5",
            link: "#80cbc4",
            accent: "#009688",
            onAccent: "#ffffff",
            danger: "#f07178",
            success: "#c3e88d",
            selection: "#425b67",
            caret: "#ffcc00",
        },
    },
    {
        id: "material-darker",
        name: "Material Darker",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#212121",
            surface: "#292929",
            border: "#3a3a3a",
            text: "#eeffff",
            textSubtle: "#b0bec5",
            link: "#82aaff",
            accent: "#ff9800",
            onAccent: "#212121",
            danger: "#f07178",
            success: "#c3e88d",
            selection: "#404040",
            caret: "#ffcc00",
        },
    },
    {
        id: "material-palenight",
        name: "Material Palenight",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#292d3e",
            surface: "#31364a",
            border: "#444267",
            text: "#a6accd",
            link: "#82aaff",
            accent: "#ab47bc",
            onAccent: "#ffffff",
            danger: "#f07178",
            success: "#c3e88d",
            selection: "#3c435e",
            caret: "#ffcc00",
        },
    },
    {
        id: "material-deep-ocean",
        name: "Material Deep Ocean",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#0f111a",
            surface: "#1a1c25",
            border: "#232737",
            text: "#a6accd",
            link: "#82aaff",
            accent: "#84ffff",
            onAccent: "#0f111a",
            danger: "#f07178",
            success: "#c3e88d",
            selection: "#1f2233",
            caret: "#ffcc00",
        },
    },
    {
        id: "material-lighter",
        name: "Material Lighter",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#fafafa",
            surface: "#eeeeee",
            border: "#e0e0e0",
            text: "#546e7a",
            link: "#6182b8",
            accent: "#00bcd4",
            danger: "#e53935",
            success: "#91b859",
            selection: "#dff1ef",
            caret: "#272727",
        },
    },
    {
        id: "monokai-pro",
        name: "Monokai Pro",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#2d2a2e",
            surface: "#403e41",
            border: "#5b595c",
            text: "#fcfcfa",
            textSubtle: "#c1c0c0",
            link: "#78dce8",
            accent: "#ffd866",
            onAccent: "#2d2a2e",
            danger: "#ff6188",
            success: "#a9dc76",
            selection: "#4a474b",
            caret: "#fcfcfa",
        },
    },
    {
        id: "rose-pine",
        name: "Rosé Pine",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#191724",
            surface: "#1f1d2e",
            border: "#403d52",
            text: "#e0def4",
            textSubtle: "#908caa",
            link: "#9ccfd8",
            accent: "#ebbcba",
            onAccent: "#191724",
            danger: "#eb6f92",
            success: "#9ccfd8",
            selection: "#403d52",
            caret: "#e0def4",
        },
    },
    {
        id: "rose-pine-moon",
        name: "Rosé Pine Moon",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#232136",
            surface: "#2a273f",
            border: "#44415a",
            text: "#e0def4",
            textSubtle: "#908caa",
            link: "#9ccfd8",
            accent: "#c4a7e7",
            onAccent: "#232136",
            danger: "#eb6f92",
            success: "#9ccfd8",
            selection: "#44415a",
            caret: "#e0def4",
        },
    },
    {
        id: "rose-pine-dawn",
        name: "Rosé Pine Dawn",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#faf4ed",
            surface: "#f2e9e1",
            border: "#dfdad9",
            text: "#575279",
            link: "#286983",
            accent: "#907aa9",
            onAccent: "#faf4ed",
            danger: "#b4637a",
            success: "#286983",
            selection: "#dfdad9",
            caret: "#575279",
        },
    },
    {
        id: "everforest-dark",
        name: "Everforest Dark",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#2d353b",
            surface: "#343f44",
            border: "#475258",
            text: "#d3c6aa",
            link: "#7fbbb3",
            accent: "#a7c080",
            onAccent: "#2d353b",
            danger: "#e67e80",
            success: "#a7c080",
            selection: "#543a48",
            caret: "#d3c6aa",
        },
    },
    {
        id: "everforest-light",
        name: "Everforest Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#fdf6e3",
            surface: "#f4f0d9",
            border: "#e6e2cc",
            text: "#5c6a72",
            link: "#3a94c5",
            accent: "#8da101",
            danger: "#f85552",
            success: "#35a77c",
            selection: "#eaedc8",
            caret: "#5c6a72",
        },
    },
    {
        id: "kanagawa",
        name: "Kanagawa",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1f1f28",
            surface: "#2a2a37",
            border: "#363646",
            text: "#dcd7ba",
            link: "#7e9cd8",
            accent: "#957fb8",
            danger: "#e46876",
            success: "#98bb6c",
            selection: "#2d4f67",
            caret: "#c8c093",
        },
    },
    {
        id: "shades-of-purple",
        name: "Shades of Purple",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#2d2b55",
            surface: "#28284e",
            border: "#3b3b76",
            text: "#ffffff",
            textSubtle: "#a599e9",
            link: "#9effff",
            accent: "#fad000",
            onAccent: "#2d2b55",
            danger: "#ec3a37",
            success: "#3ad900",
            selection: "#5c3d99",
            caret: "#fad000",
        },
    },
    {
        id: "cobalt2",
        name: "Cobalt2",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#193549",
            surface: "#1f4662",
            border: "#234e6d",
            text: "#ffffff",
            link: "#ffc600",
            accent: "#ffc600",
            onAccent: "#193549",
            danger: "#ff628c",
            success: "#3ad900",
            selection: "#0050a4",
            caret: "#ffc600",
        },
    },
    {
        id: "synthwave-84",
        name: "SynthWave '84",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#262335",
            surface: "#34294f",
            border: "#495495",
            text: "#ffffff",
            link: "#36f9f6",
            accent: "#ff7edb",
            onAccent: "#262335",
            danger: "#fe4450",
            success: "#72f1b8",
            selection: "#45425a",
            caret: "#f97e72",
        },
    },
    {
        id: "horizon",
        name: "Horizon",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1c1e26",
            surface: "#232530",
            border: "#2e303e",
            text: "#d5d8da",
            link: "#25b0bc",
            accent: "#e95378",
            onAccent: "#ffffff",
            danger: "#f43e5c",
            success: "#29d398",
            selection: "#343647",
            caret: "#e95378",
        },
    },
    {
        id: "panda",
        name: "Panda",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#292a2b",
            surface: "#31353a",
            border: "#3e4250",
            text: "#e6e6e6",
            link: "#45a9f9",
            accent: "#ff75b5",
            onAccent: "#292a2b",
            danger: "#ff4b82",
            success: "#19f9d8",
            selection: "#404954",
            caret: "#ffb86c",
        },
    },
    {
        id: "andromeda",
        name: "Andromeda",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#23262e",
            surface: "#2b2f38",
            border: "#373941",
            text: "#d5ced9",
            link: "#00e8c6",
            accent: "#c74ded",
            onAccent: "#ffffff",
            danger: "#ee5d43",
            success: "#96e072",
            selection: "#3d4351",
            caret: "#00e8c6",
        },
    },
    {
        id: "moonlight",
        name: "Moonlight",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#222436",
            surface: "#2f334d",
            border: "#3b4261",
            text: "#c8d3f5",
            link: "#82aaff",
            accent: "#c099ff",
            onAccent: "#222436",
            danger: "#ff757f",
            success: "#c3e88d",
            selection: "#2d3f76",
            caret: "#82aaff",
        },
    },
    {
        id: "poimandres",
        name: "Poimandres",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1b1e28",
            surface: "#252b37",
            border: "#303340",
            text: "#e4f0fb",
            textSubtle: "#a6accd",
            link: "#add7ff",
            accent: "#5de4c7",
            onAccent: "#1b1e28",
            danger: "#d0679d",
            success: "#5de4c7",
            selection: "#303340",
            caret: "#a6accd",
        },
    },
    {
        id: "oceanic-next",
        name: "Oceanic Next",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#1b2b34",
            surface: "#343d46",
            border: "#4f5b66",
            text: "#d8dee9",
            link: "#6699cc",
            accent: "#6699cc",
            onAccent: "#1b2b34",
            danger: "#ec5f67",
            success: "#99c794",
            selection: "#4f5b66",
            caret: "#c0c5ce",
        },
    },
    {
        id: "vitesse-dark",
        name: "Vitesse Dark",
        origin: "popular",
        appearance: "dark",
        palette: {
            background: "#121212",
            surface: "#1c1c1c",
            border: "#2a2a2a",
            text: "#dbd7ca",
            link: "#4d9375",
            accent: "#4d9375",
            onAccent: "#121212",
            danger: "#cb7676",
            success: "#4d9375",
            selection: "#2a2a2a",
            caret: "#dbd7ca",
        },
    },
    {
        id: "vitesse-light",
        name: "Vitesse Light",
        origin: "popular",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#f7f7f7",
            border: "#e7e7e7",
            text: "#393a34",
            link: "#1c6b48",
            accent: "#1c6b48",
            onAccent: "#ffffff",
            danger: "#ab5959",
            success: "#1e754f",
            selection: "#e8e8e8",
            caret: "#393a34",
        },
    },
];
