import type {ThemeDefinition} from "@/theme/themeTypes";

// Themes that ship with VS Code.
export const vscodeThemes: ThemeDefinition[] = [
    {
        id: "vscode-dark-modern",
        name: "Dark Modern",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#1f1f1f",
            surface: "#2a2a2a",
            border: "#3c3c3c",
            text: "#cccccc",
            link: "#4daafc",
            accent: "#0078d4",
            onAccent: "#ffffff",
            danger: "#f85149",
            success: "#2ea043",
            selection: "#264f78",
            caret: "#aeafad",
        },
    },
    {
        id: "vscode-light-modern",
        name: "Light Modern",
        origin: "vscode",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#f8f8f8",
            border: "#e5e5e5",
            text: "#3b3b3b",
            link: "#005fb8",
            accent: "#005fb8",
            onAccent: "#ffffff",
            danger: "#e51400",
            success: "#2ea043",
            selection: "#add6ff",
            caret: "#000000",
        },
    },
    {
        id: "vscode-dark-plus",
        name: "Dark+",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#1e1e1e",
            surface: "#252526",
            border: "#3c3c3c",
            text: "#d4d4d4",
            link: "#3794ff",
            accent: "#0e639c",
            onAccent: "#ffffff",
            danger: "#f48771",
            success: "#89d185",
            selection: "#264f78",
            caret: "#aeafad",
        },
    },
    {
        id: "vscode-light-plus",
        name: "Light+",
        origin: "vscode",
        appearance: "light",
        palette: {
            background: "#ffffff",
            surface: "#f3f3f3",
            border: "#e4e4e4",
            text: "#1e1e1e",
            link: "#006ab1",
            accent: "#007acc",
            onAccent: "#ffffff",
            danger: "#e51400",
            success: "#388a34",
            selection: "#add6ff",
            caret: "#000000",
        },
    },
    {
        id: "vscode-monokai",
        name: "Monokai",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#272822",
            surface: "#31322b",
            border: "#414339",
            text: "#f8f8f2",
            link: "#66d9ef",
            accent: "#f92672",
            onAccent: "#f8f8f2",
            danger: "#f44747",
            success: "#a6e22e",
            selection: "#49483e",
            caret: "#f8f8f0",
        },
    },
    {
        id: "vscode-solarized-dark",
        name: "Solarized Dark",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#002b36",
            surface: "#073642",
            border: "#0d4a58",
            text: "#93a1a1",
            link: "#268bd2",
            accent: "#2aa198",
            onAccent: "#002b36",
            danger: "#dc322f",
            success: "#859900",
            selection: "#274642",
            caret: "#d30102",
        },
    },
    {
        id: "vscode-solarized-light",
        name: "Solarized Light",
        origin: "vscode",
        appearance: "light",
        palette: {
            background: "#fdf6e3",
            surface: "#eee8d5",
            border: "#ddd6c1",
            text: "#586e75",
            link: "#268bd2",
            accent: "#268bd2",
            onAccent: "#fdf6e3",
            danger: "#dc322f",
            success: "#859900",
            selection: "#e0d9bf",
            caret: "#657b83",
        },
    },
    {
        id: "vscode-quiet-light",
        name: "Quiet Light",
        origin: "vscode",
        appearance: "light",
        palette: {
            background: "#f5f5f5",
            surface: "#ececec",
            border: "#dcdcdc",
            text: "#333333",
            link: "#4b69c6",
            accent: "#705697",
            onAccent: "#ffffff",
            danger: "#aa3731",
            success: "#448c27",
            selection: "#c9d0d9",
            caret: "#54494b",
        },
    },
    {
        id: "vscode-abyss",
        name: "Abyss",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#000c18",
            surface: "#051336",
            border: "#2b2b4a",
            text: "#6688cc",
            link: "#ddbb88",
            accent: "#225588",
            onAccent: "#ffffff",
            danger: "#f14c4c",
            success: "#22aa44",
            selection: "#770811",
            caret: "#ddbb88",
        },
    },
    {
        id: "vscode-kimbie-dark",
        name: "Kimbie Dark",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#221a0f",
            surface: "#362712",
            border: "#51412c",
            text: "#d3af86",
            link: "#8ab1b0",
            accent: "#f79a32",
            onAccent: "#221a0f",
            danger: "#dc3958",
            success: "#889b4a",
            selection: "#5c4225",
            caret: "#d3af86",
        },
    },
    {
        id: "vscode-tomorrow-night-blue",
        name: "Tomorrow Night Blue",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#002451",
            surface: "#001c40",
            border: "#003f8e",
            text: "#ffffff",
            link: "#bbdaff",
            accent: "#ebbbff",
            onAccent: "#002451",
            danger: "#ff9da4",
            success: "#d1f1a9",
            selection: "#003f8e",
            caret: "#ffffff",
        },
    },
    {
        id: "vscode-red",
        name: "Red",
        origin: "vscode",
        appearance: "dark",
        palette: {
            background: "#390000",
            surface: "#4a0000",
            border: "#660000",
            text: "#f8f8f8",
            link: "#ffd0aa",
            accent: "#cc3333",
            onAccent: "#ffffff",
            danger: "#ff6666",
            success: "#9bc485",
            selection: "#750000",
            caret: "#ffaaaa",
        },
    },
];
