services:
  traefik:
    image: traefik:v3.6
    command:
#      - "--api.insecure=true" # Enable Traefik dashboard and API without authentication (remove for production; for testing/debugging only)
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yaml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml:ro
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
