package co.jinear.core.model.entity.account;

import co.jinear.core.model.entity.BaseEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "account_password")
public class AccountPassword extends BaseEntity {

    @Id
    @GeneratedValue(generator = "ULID")
    @GenericGenerator(
            name = "ULID",
            strategy = "co.jinear.core.config.idgenerator.ULIDIdGenerator")
    @Column(name = "account_password_id")
    private String accountPasswordId;

    @Column(name = "account_id",unique = true)
    private String accountId;

    @Column(name = "password")
    private String password;

    @Column(name = "auto_generated")
    private Boolean autoGenerated;

    @JsonIgnore
    @ToString.Exclude
    @OneToOne
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "account_id", insertable = false, updatable = false)
    private Account account;
}
