variables:
  PROJECT_NAME: jinear-core
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/140crafts/jinear/projects/jinear-core:${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE_LATEST: registry.gitlab.com/140crafts/jinear/projects/jinear-core:latest

stages:
  - build
  - deploy

default:
  image: docker:latest

build:
  stage: build
  script:
    - unset DOCKER_HOST
    - docker build -t ${CONTAINER_IMAGE} .
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker push ${CONTAINER_IMAGE}
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: manual

deploy-latest:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker pull ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE_LATEST}
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  needs:
    - build