variables:
  PROJECT_NAME: jinear-core

stages:
  - build
  - deploy-stg
  - deploy-prod

default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_CREDS
    - gcloud config set project selam-255606

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: manual
  script:
    - gcloud builds submit --tag gcr.io/selam-255606/$PROJECT_NAME:latest

deploy-staging:
  stage: deploy-stg
  needs:
    - job: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: manual
  script:
    - gcloud run deploy $PROJECT_NAME-staging --image gcr.io/selam-255606/$PROJECT_NAME:latest --allow-unauthenticated --platform managed --region europe-west4 --vpc-connector=crafts-generic-vpc-conn --vpc-egress=all-traffic --add-cloudsql-instances=selam-255606:europe-west4:crafts-general --port=8008 --use-http2 --memory=1024Mi --max-instances=1 --set-env-vars=CLOUD_RUN_PROJECT_HASH=2355s6tobq,spring_profiles_active=stg --service-account=fitpath-dev-admin@selam-255606.iam.gserviceaccount.com
    - gcloud run services update-traffic $PROJECT_NAME-staging --to-latest --region europe-west4

deploy-prod:
  stage: deploy-prod
  needs:
    - job: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
  script:
    - gcloud run deploy $PROJECT_NAME --image gcr.io/selam-255606/$PROJECT_NAME:latest --allow-unauthenticated --platform managed --region europe-west4 --vpc-connector=crafts-generic-vpc-conn --vpc-egress=private-ranges-only --add-cloudsql-instances=selam-255606:europe-west4:crafts-general --port=8008 --use-http2 --memory=4Gi --timeout=600 --max-instances=10 --concurrency 140 --set-env-vars=CLOUD_RUN_PROJECT_HASH=2355s6tobq,spring_profiles_active=prod --service-account=fitpath-dev-admin@selam-255606.iam.gserviceaccount.com
    - gcloud run services update-traffic $PROJECT_NAME --to-latest --region europe-west4