"use client";

import React, { useEffect } from "react";
import { useAppDispatch, useTypedSelector } from "@/store/store";
import { selectCurrentAccount } from "@/slice/accountSlice";
import { popPasswordChangeModal } from "@/slice/modalSlice";

interface ForcePasswordChangeCheckerProps {

}

const ForcePasswordChangeChecker: React.FC<ForcePasswordChangeCheckerProps> = ({}) => {
  const dispatch = useAppDispatch();
  const currentAccount = useTypedSelector(selectCurrentAccount);
  const passwordAutoGenerated = currentAccount?.passwordAutoGenerated;

  useEffect(() => {
    passwordAutoGenerated && dispatch(popPasswordChangeModal({ forced: true, visible: true }));
  }, [passwordAutoGenerated, dispatch]);

  return null;
};

export default ForcePasswordChangeChecker;