package co.jinear.core.manager.management;

import co.jinear.core.model.dto.PageDto;
import co.jinear.core.model.dto.account.AccountDto;
import co.jinear.core.model.dto.team.member.TeamMemberDto;
import co.jinear.core.model.dto.workspace.DetailedWorkspaceMemberDto;
import co.jinear.core.model.request.management.AdminAccountCreateRequest;
import co.jinear.core.model.request.management.AdminAccountPasswordUpdateRequest;
import co.jinear.core.model.response.BaseResponse;
import co.jinear.core.model.response.account.AccountRetrieveResponse;
import co.jinear.core.model.response.management.AdminAccountListingResponse;
import co.jinear.core.model.response.team.TeamMembershipsResponse;
import co.jinear.core.model.response.workspace.AccountWorkspacesResponse;
import co.jinear.core.model.vo.account.AccountInitializeVo;
import co.jinear.core.model.vo.account.password.AccountPasswordVo;
import co.jinear.core.service.SessionInfoService;
import co.jinear.core.service.account.AccountInitializeService;
import co.jinear.core.service.account.AccountPasswordService;
import co.jinear.core.service.account.AccountRetrieveService;
import co.jinear.core.service.team.member.TeamMemberRetrieveService;
import co.jinear.core.service.workspace.member.WorkspaceMemberListingService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;

import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class AdminAccountManager {

    private final SessionInfoService sessionInfoService;
    private final AccountRetrieveService accountRetrieveService;
    private final AccountInitializeService accountInitializeService;
    private final AccountPasswordService accountPasswordService;
    private final WorkspaceMemberListingService workspaceMemberListingService;
    private final TeamMemberRetrieveService teamMemberRetrieveService;

    public AdminAccountListingResponse retrieveAllAccounts(Integer page) {
        String accountId = sessionInfoService.currentAccountId();
        log.info("Admin retrieve all accounts has started. accountId: {}, page: {}", accountId, page);
        Page<AccountDto> accountDtoPage = accountRetrieveService.retrieveAllAccounts(page);
        AdminAccountListingResponse adminAccountListingResponse = new AdminAccountListingResponse();
        adminAccountListingResponse.setAccountDtoPage(new PageDto<>(accountDtoPage));
        return adminAccountListingResponse;
    }

    public AccountRetrieveResponse createAccount(AdminAccountCreateRequest request) {
        String accountId = sessionInfoService.currentAccountId();
        log.info("Admin create account has started. accountId: {}, request: {}", accountId, request);
        AccountInitializeVo accountInitializeVo = new AccountInitializeVo();
        accountInitializeVo.setEmail(request.getEmail());
        accountInitializeVo.setPassword(request.getPassword());
        accountInitializeVo.setEmailConfirmed(Boolean.TRUE);
        accountInitializeVo.setInitialWorkspaceCreationSkipped(Boolean.TRUE);
        accountInitializeVo.setLocale(request.getLocale());
        AccountDto accountDto = accountInitializeService.initializeAccount(accountInitializeVo);
        AccountRetrieveResponse accountRetrieveResponse = new AccountRetrieveResponse();
        accountRetrieveResponse.setAccountDto(accountDto);
        return accountRetrieveResponse;
    }

    public BaseResponse updatePassword(String targetAccountId, AdminAccountPasswordUpdateRequest request) {
        String accountId = sessionInfoService.currentAccountId();
        log.info("Admin update account password has started. accountId: {}, targetAccountId: {}", accountId, targetAccountId);
        accountRetrieveService.retrieve(targetAccountId);
        AccountPasswordVo accountPasswordVo = AccountPasswordVo.builder()
                .accountId(targetAccountId)
                .clearText(request.getNewPassword())
                .autoGenerated(Boolean.TRUE)
                .build();
        accountPasswordService.updateAccountPassword(accountPasswordVo);
        return new BaseResponse();
    }

    public AccountWorkspacesResponse retrieveWorkspaceMemberships(String targetAccountId) {
        String accountId = sessionInfoService.currentAccountId();
        log.info("Admin retrieve account workspace memberships has started. accountId: {}, targetAccountId: {}", accountId, targetAccountId);
        accountRetrieveService.retrieve(targetAccountId);
        List<DetailedWorkspaceMemberDto> workspaces = workspaceMemberListingService.retrieveAccountsWorkspaceMemberships(targetAccountId);
        AccountWorkspacesResponse accountWorkspacesResponse = new AccountWorkspacesResponse();
        accountWorkspacesResponse.setWorkspaces(workspaces);
        return accountWorkspacesResponse;
    }

    public TeamMembershipsResponse retrieveTeamMemberships(String targetAccountId) {
        String accountId = sessionInfoService.currentAccountId();
        log.info("Admin retrieve account team memberships has started. accountId: {}, targetAccountId: {}", accountId, targetAccountId);
        accountRetrieveService.retrieve(targetAccountId);
        List<TeamMemberDto> teamMemberDtoList = teamMemberRetrieveService.retrieveAllTeamMembershipsOfAnAccount(targetAccountId);
        TeamMembershipsResponse teamMembershipsResponse = new TeamMembershipsResponse();
        teamMembershipsResponse.setTeamMemberDtoList(teamMemberDtoList);
        return teamMembershipsResponse;
    }
}
