package co.jinear.core.model.vo.account.password;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.checkerframework.checker.nullness.qual.Nullable;

@Getter
@Setter
@Builder
@ToString
public class AccountPasswordVo {
    private String accountId;
    @Nullable
    @ToString.Exclude
    private String clearText;
    @Nullable
    private Boolean autoGenerated;
}
